<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-31T03:37:11Z" name="Default suite" finished-at="2022-07-31T03:37:35Z" duration-ms="23636">
    <groups>
    </groups>
    <test started-at="2022-07-31T03:37:11Z" name="Default test" finished-at="2022-07-31T03:37:35Z" duration-ms="23636">
      <class name="com.sample.test.demo.tests.DemoTest">
        <test-method is-config="true" signature="init()[pri:0, instance:com.sample.test.demo.tests.DemoTest@6440112d]" started-at="2022-07-31T03:37:11Z" name="init" finished-at="2022-07-31T03:37:12Z" duration-ms="1569" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="demoTest()[pri:0, instance:com.sample.test.demo.tests.DemoTest@6440112d]" started-at="2022-07-31T03:37:12Z" name="demoTest" finished-at="2022-07-31T03:37:24Z" duration-ms="11031" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoTest -->
        <test-method signature="demoTest2()[pri:1, instance:com.sample.test.demo.tests.DemoTest@6440112d]" started-at="2022-07-31T03:37:24Z" name="demoTest2" finished-at="2022-07-31T03:37:34Z" duration-ms="10858" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.sample.test.demo.tests.DemoTest.demoTest2(DemoTest.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoTest2 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.sample.test.demo.tests.DemoTest@6440112d]" started-at="2022-07-31T03:37:34Z" name="tearDown" finished-at="2022-07-31T03:37:35Z" duration-ms="150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.sample.test.demo.tests.DemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
